### ISSUE TITLE
No aerodynamic forces on non-active vessels loaded into physics range

### ISSUE THREAD

**Issue by fredericohpandolfo** [ferram4/Ferram-Aerospace-Research#162] opened 2016-12-24 11:59 UTC
Zero lift, drag, etc when change ships that are in the physics range.
To reproduce is simple: Just spawn 2 aircrafts in KSC, and switch the active ship. The new active ship are affected.
This video has what i done to reproduce the problem.
https://youtu.be/nERq4PSVO10

This is a clean install, only with far and its dependencies (module manager and modular flight integrator.)

[KSP.zip](https://github.com/ferram4/Ferram-Aerospace-Research/files/671753/KSP.zip)

**Comment by ferram4** [comment] 2016-12-24 16:53
I have reproduced the issue, I'll see what's going on.

**Comment by ferram4** [comment] 2016-12-29 20:33
I believe that this has been fixed in the latest dev build.  I reproduce it now, but there's a chance that I might have missed an edge case.  In the meantime though, I'm closing this as it seems to be fixed; comment if something similar comes up again.

**Closed by ferram4** 2016-12-29 20:33 UTC
