### ISSUE TITLE
parachute not showing in staging with module manager 2.7.5

### ISSUE THREAD

**Issue by xeonke** [ferram4/Ferram-Aerospace-Research#167] opened 2017-01-28 18:09 UTC
hello.

After a fresh install i installed al my mods again.
I noticed that the parachute would not show up in the staging also no right click menu during flight
If i removed Far then i got my parachute back

I made a seperate clean install with only FAR.
The included module manager = working parachute.
Module manager 2.7.5 = no parachutes
Module manager 2.7.5 with out Far = working parachute.

hope you can fix this as i find your mode on of my must have's for ksp

with kind regards
xeonke

**Comment by ferram4** [comment] 2017-01-30 01:39
I cannot reproduce this issue with MM 2.7.5, MFI 1.2.3 and the dev build of FAR on KSP 1.2.2.  If you are not using that combination then FAR will not function properly.  If you are, then I need complete reproduction steps and a full copy of KSP.log.

**Comment by xeonke** [comment] 2017-02-01 20:54
[KSP.zip](https://github.com/ferram4/Ferram-Aerospace-Research/files/746101/KSP.zip)
[ModularFlightIntegrator-1.2.3.0.zip](https://github.com/ferram4/Ferram-Aerospace-Research/files/746102/ModularFlightIntegrator-1.2.3.0.zip)
[Ferram_Aerospace_Research-v0.15.7.2_Lanchester.zip](https://github.com/ferram4/Ferram-Aerospace-Research/files/746103/Ferram_Aerospace_Research-v0.15.7.2_Lanchester.zip)
[ModuleManager.2.7.5.zip](https://github.com/ferram4/Ferram-Aerospace-Research/files/746106/ModuleManager.2.7.5.zip)

In the zip file is the log file.
Also the used mods for the clean install

Reproduction steps
Install fresh copy of ksp 1.2.2 from website
Copy gamedata folder from FAR (parachute works if you run the game)
Copy modulemanager 2.7.5 dll into gamedata folder and delete modulemanger 2.6.25 that came with far
Parachutes don't work anymore.

I then also tried to copy a fresh copy of MFI but keeping the 2.7.5 module manger > parachutes don't work.

OS is Win server 2012R2 for games this is windows 8.1
Direct x 11.2

With kind regards
Xeonke

**Comment by blowfishpro** [comment] 2017-02-01 21:01
No released version of FAR works with KSP 1.2.2.  That is probably your issue.

**Comment by ferram4** [comment] 2017-02-02 01:39
Yep, this is a case of using a version of FAR that is not compatible with KSP 1.2.2.  Closing.

**Closed by ferram4** 2017-02-02 01:39 UTC

**Comment by xeonke** [comment] 2017-02-02 19:41
ok sorry then for this
