### ISSUE TITLE
Problem with displaying numbers <0.1

### ISSUE THREAD

**Issue by glilienthal** [ferram4/Ferram-Aerospace-Research#186] opened 2017-04-15 16:38 UTC
![2017-04-15 far error](https://cloud.githubusercontent.com/assets/8526242/25065167/9a40ba14-220a-11e7-8a5d-956cbf5de869.png)
![2017-04-15 far error2](https://cloud.githubusercontent.com/assets/8526242/25065166/9a3d61a2-220a-11e7-986a-ac23cb0fe000.png)

It looks to me that the FAR flight data display displays 0.01 as 0.1  and 0.001 also as 0.1. 
 (cf. attached screenshots, look at sideforce.)

**Comment by ferram4** [comment] 2017-04-18 02:49
I cannot reproduce this issue, and it matches #183.  This means that you are not using the latest dev build; update and it will be fixed.

**Closed by ferram4** 2017-04-18 02:49 UTC

**Comment by glilienthal** [comment] 2017-04-19 07:51
You are right. It is working with the newest version now.
