### ISSUE TITLE
Crash while approaching a splashed down craft

### ISSUE THREAD

**Issue by Mighty11** [ferram4/Ferram-Aerospace-Research#190] opened 2017-05-27 21:49 UTC
KSP 1.2.2 With FAR De Laval. Game crashes as you approach a craft with status "splashed down" in water or on the shores. Approaching on a landed craft works normally. The crash happens when you come to 200m distance ether flying or surfing on the water.

Here is the crash report and save. https://www.dropbox.com/s/yxwuegm3eg1nnfs/KSP%20crash.rar?dl=0

**Comment by ferram4** [comment] 2017-05-27 22:49
Confirmed, I pushed a new dev build that should fix it.  Turns out that there's a single frame on loading where NaN can slip into the calculations due to the risk of a divide-by-zero.  I added a check for the NaN to prevent things from breaking.

**Comment by ferram4** [comment] 2017-06-04 20:12
Well, it looks like the build a few days ago fixed that, so I'm closing this.

**Closed by ferram4** 2017-06-04 20:12 UTC
