### ISSUE TITLE
Incorrect Determination of Main Axis for Unconventional Crafts

### ISSUE THREAD

**Issue by mjn33** [ferram4/Ferram-Aerospace-Research#78] opened 2015-05-18 18:52 UTC
**Operating System:** Fedora 21 (Linux) x86-64

Using FAR from the master branch, commit 065777eb9ee5d7feab5d12d55a6ef1b18cade1f4
Mods installed:
- ModularFlightIntegrator v1.0.0
- ModuleManager v2.6.3

**Reproduction steps:**
1. (Optionally) Disable aerodynamic failures
2. Go to the SPH and load the craft file at https://dl.dropboxusercontent.com/u/15422248/farbug3/Aeroscoop%20mk2.craft
3. Perform an AoA sweep on the craft, note the unusually high values for Cd, Cl, etc.
4. Launch vessel

**Expected result:**
The craft experiences a high but reasonable amount of lift / drag.

**Actual result:**
If aerodynamic failures are enabled, many parts will explode shortly after the
craft is loaded. Without aerodynamic failures, the craft visibly "twitches" and
enabling "Display Aero Forces In Flight" shows these phantom forces. From my
testing, the first version this is reproducible is at commit
fc4afd910d343d26775d7d76032d6a056c032e6b.

Contents of Player.log here: https://dl.dropboxusercontent.com/u/15422248/farbug3/Player.log
Video displaying the issue here: https://dl.dropboxusercontent.com/u/15422248/farbug3/cut2.mp4

**Comment by futrtrubl** [comment] 2015-05-19 00:16
Looks like the main axis issue, looks like it's off by about 45 degrees from where the lift/drag minimum is. Go to trans-sonic design and show the curves there and post that pic.

**Comment by ferram4** [comment] 2015-05-19 02:20
Yeah, to be honest, I don't see how I'd be able to fix this.  I mean, how am I supposed to determine the intended forward direction of _that_ thing?

I'll keep trying to fix this, but I consider this to be ultra-low priority because, quite frankly, it's designed to break the model.  And if someone comes in intending to break the model, there's really nothing I can do to protect against it.

**Comment by futrtrubl** [comment] 2015-05-19 07:52
Could we lock the intended forward direction to upwards in the VAB and towards the doors in the SPH?

**Comment by mjn33** [comment] 2015-05-19 13:44
I did guess that the weirdness of the design was breaking some (reasonable)
assumption made. Anyway, here are a few more results from my testing:

**Tested FAR v0.15.1 "Fanno" release**
The cross-section area curves appear far off from the vehicle itself (bottom right hand side of the screenshot).
[Screenshot](https://dl.dropboxusercontent.com/u/15422248/farbug3/screenshot25.png)

**Tested 596a2a5faae936edace3d580369c60dada2d3818**
Again same as Fanno, slightly different curves from the static analysis, mostly
the same shape.
[Screenshot](https://dl.dropboxusercontent.com/u/15422248/farbug3/screenshot26.png)

**Tested 065777eb9ee5d7feab5d12d55a6ef1b18cade1f4**
When I clicked "Toggle Cross-Section Area Curves", it doesn't seem to produce
the curves at all (not sure if they are just even further off in the distance somewhere).
[Screenshot](https://dl.dropboxusercontent.com/u/15422248/farbug3/screenshot27.png)

**Tested 07b549e97254ea1884daa0be283c39f921124721**
Issue seems fixed (for this craft at least).
[Screenshot](https://dl.dropboxusercontent.com/u/15422248/farbug3/screenshot24.png)

**Comment by ferram4** [comment] 2015-05-19 17:36
Yeah, for this craft.  I'll leave this issue open for now because there are, inevitably, lots of other failure points to this that need to be addressed.

**Comment by mjn33** [comment] 2015-05-19 21:07
Ok, I've been doing yet more testing:

**Tested 07b549e97254ea1884daa0be283c39f921124721**
Using a slightly different version of the old craft (the "mk3"), the curves are far away from the craft itself.

[Craft file](https://dl.dropboxusercontent.com/u/15422248/farbug3/Aeroscoop%20mk3.craft)
[Screenshot](https://dl.dropboxusercontent.com/u/15422248/farbug3/screenshot30.png)

Going through the code, I decided to revert the fix introduced with 07b549e97254ea1884daa0be283c39f921124721 and replace `return axis` with `return axis.normalized`. To my amazement, it seems to have helped; the curves for the mk2 craft appear in the wrong place but they at least appear now. Reverting the change also made the mk3 version work again. The weird thing is although the curves for the mk2 craft appear in the wrong place, the inner wings flat-facing the air seem to be generating more drag and stalling, where as before with the fix they didn't seem to produce any significant amount of drag ([screenshot](https://dl.dropboxusercontent.com/u/15422248/farbug3/screenshot33.png)). Tested oldFAR on KSP 0.90 and the wings produced more drag and were stalling (as I would expect).

[Patch diff](https://gist.github.com/mjn33/50800f05643f062a72a2)
[Screenshot of mk2 with my patch](https://dl.dropboxusercontent.com/u/15422248/farbug3/screenshot28.png)
[Screenshot of mk3 with my patch](https://dl.dropboxusercontent.com/u/15422248/farbug3/screenshot29.png)

I admit I'm starting to get out of my depth here, but I figured these observations might be useful in any case.

**Comment by ferram4** [comment] 2015-05-20 01:48
The main issue is that the damn wing box breaks everything.  The change was purely to ignore wings in determining the main axis, which worked, but main axis doesn't play into the drag of the wings themselves at all.  In fact, my tests on the latest build show that the flat wings are stalled and that drag is quite high on the whole thing.

I'll add the axis.normalized change, that makes sense, but I can't reproduce the non-stalling wings issue.

**Comment by mjn33** [comment] 2015-05-20 13:23
Just checked, 33d0c42eaeaf9697f5113a3a43b6fee49822d80c fixed the low drag on the wings.

**Comment by mjn33** [comment] 2015-05-24 19:26
More tests again, using 15da204a8c9bd9fe6ec9eac294892b8b7c479bd1. The M-2x2 Structural Panel seems to have some issues, I think they are main axis related (not 100% sure).

They on their own seem to have drag flat facing one way, but not the other. Test craft "FAR Firehound Test1" and "FAR Firehound Test3" use structural panels but are rotated different ways. Both when attached to the FAR Firehound don't seem to produce any significant amount of drag. When detached you can observe that the panels on the "FAR Firehound Test3" fly away much quicker.

The "FAR Firehound Test2" puts another panel on top of the "FAR Firehound Test1", when detached they immediately ping off at high speed.

[Single panel main axis](https://dl.dropboxusercontent.com/u/15422248/farbug3cont/screenshot6.png)
[Double panel main axis](https://dl.dropboxusercontent.com/u/15422248/farbug3cont/screenshot7.png)
[FAR Firehound Test1 main axis](https://dl.dropboxusercontent.com/u/15422248/farbug3cont/screenshot2.png)
[FAR Firehound Test2 main axis](https://dl.dropboxusercontent.com/u/15422248/farbug3cont/screenshot3.png)
[FAR Firehound Test3 main axis](https://dl.dropboxusercontent.com/u/15422248/farbug3cont/screenshot8.png)


[FAR Firehound Test1 in flight](https://dl.dropboxusercontent.com/u/15422248/farbug3cont/screenshot0.png)
[Structural panel, no drag](https://dl.dropboxusercontent.com/u/15422248/farbug3cont/screenshot1.png)
[FAR Firehound Test2 at runway](https://dl.dropboxusercontent.com/u/15422248/farbug3cont/screenshot4.png)
[Self destructing wing](https://dl.dropboxusercontent.com/u/15422248/farbug3cont/screenshot5.png)

[FAR Firehound Test1.craft](https://dl.dropboxusercontent.com/u/15422248/farbug3cont/FAR%20Firehound%20Test1.craft)
[FAR Firehound Test2.craft](https://dl.dropboxusercontent.com/u/15422248/farbug3cont/FAR%20Firehound%20Test2.craft)
[FAR Firehound Test3.craft](https://dl.dropboxusercontent.com/u/15422248/farbug3cont/FAR%20Firehound%20Test3.craft)

[Player.log](https://dl.dropboxusercontent.com/u/15422248/farbug3cont/Player.log)

**Comment by ferram4** [comment] 2015-06-26 23:37
Although this comment is late, the structural panel issues should have been addressed in Garabedian.

**Comment by ferram4** [comment] 2016-12-20 05:12
I believe that all of these issues have been resolved, so I'm closing this.

**Closed by ferram4** 2016-12-20 05:12 UTC
