### ISSUE TITLE
Attaching medium landing gear+B9 PW removes far(no air,drag/lift,etc).

### ISSUE THREAD

**Issue by jelmew** [ferram4/Ferram-Aerospace-Research#108] opened 2015-08-25 12:28 UTC
This happens on KSP 1.0.4
64 bits.

Mods, Far+B9 PW.

Attaching Medium landing gear(stock) to B9 Procedural wings breaks far. No lift at all. Can consistently reproduce this isue.

Log:

[LOG 14:19:43.318] Updating vessel voxel for Long glider
[EXC 14:19:43.387] IndexOutOfRangeException: Array index is out of range.
	FerramAerospaceResearch.FARAeroComponents.VehicleAerodynamics.CalculateCrossSectionSecondDerivs (FerramAerospaceResearch.FARPartGeometry.VoxelCrossSection[] vehicleCrossSection, Int32 oneSidedFilterLength, Int32 frontIndex, Int32 backIndex, Double sectionThickness)
	FerramAerospaceResearch.FARAeroComponents.VehicleAerodynamics.GaussianSmoothCrossSections (FerramAerospaceResearch.FARPartGeometry.VoxelCrossSection[] vehicleCrossSection, Double stdDevCutoff, Double lengthPercentFactor, Double sectionThickness, Double length, Int32 frontIndex, Int32 backIndex, Int32 areaSmoothingIterations, Int32 derivSmoothingIterations)
	FerramAerospaceResearch.FARAeroComponents.VehicleAerodynamics.CalculateVesselAeroProperties ()
	FerramAerospaceResearch.FARAeroComponents.VehicleAerodynamics.CreateVoxel ()
	UnityEngine.Debug:LogException(Exception)
	FerramAerospaceResearch.FARThreading.ThreadSafeDebugLogger:Update()
[LOG 14:19:45.506] [Long glider]: ground contact! - error: 0.035m
[LOG 14:19:45.506] Unpacking Long glider
[LOG 14:19:45.584] Updating vessel voxel for Long glider
[LOG 14:19:45.630] Tac.FuelBalanceController[FFE7EEF6][631.50]: Rebuilding resource lists.
[LOG 14:19:45.660] [CurrencyConverter for Fundraising Campaign]: 0 Reputation taken, yields 0 Funds
[LOG 14:19:45.696] Tac.FuelBalanceController[FFE7EEF6][631.54]: Rebuilding resource lists.
[EXC 14:19:45.700] IndexOutOfRangeException: Array index is out of range.
	FerramAerospaceResearch.FARAeroComponents.VehicleAerodynamics.CalculateCrossSectionSecondDerivs (FerramAerospaceResearch.FARPartGeometry.VoxelCrossSection[] vehicleCrossSection, Int32 oneSidedFilterLength, Int32 frontIndex, Int32 backIndex, Double sectionThickness)
	FerramAerospaceResearch.FARAeroComponents.VehicleAerodynamics.GaussianSmoothCrossSections (FerramAerospaceResearch.FARPartGeometry.VoxelCrossSection[] vehicleCrossSection, Double stdDevCutoff, Double lengthPercentFactor, Double sectionThickness, Double length, Int32 frontIndex, Int32 backIndex, Int32 areaSmoothingIterations, Int32 derivSmoothingIterations)
	FerramAerospaceResearch.FARAeroComponents.VehicleAerodynamics.CalculateVesselAeroProperties ()
	FerramAerospaceResearch.FARAeroComponents.VehicleAerodynamics.CreateVoxel ()
	UnityEngine.Debug:LogException(Exception)
	FerramAerospaceResearch.FARThreading.ThreadSafeDebugLogger:Update()

**Comment by ferram4** [comment] 2015-08-25 12:37
Using the same exact setup, I cannot reproduce any issues of the sort.  Similar issues were fixed in the dev build not too long ago that should be released later today.

**Closed by ferram4** 2015-08-25 12:37 UTC
