### ISSUE TITLE
Weird drag behaviour

### ISSUE THREAD

**Issue by lilbat** [ferram4/Ferram-Aerospace-Research#208] opened 2017-06-28 14:32 UTC
I was watching aero forces troughout my re-entry and i've noticed that  some parts were not producing drag (at about 2000 m/s) especially my front part and when i landed some parts were producing a lot of drag but i wasn't moving.
![20170628162052_1](https://user-images.githubusercontent.com/29755851/27642417-0999f9f4-5c1f-11e7-8bb2-ad1355267928.jpg)

So is it just a visual bug or is it a real issue?

**Comment by ferram4** [comment] 2017-06-28 21:25
I need reproduction steps.  I have no idea what is going on if you don't tell me what you've done.

**Comment by lilbat** [comment] 2017-06-29 10:12
For the reproductions steps i've just flew this SSTO into orbit (no docking or something else i just stayed at about 100 km of kerbin) then i landed at the KSC and while i was on my way back to the KSC i've activated the option to see the aero forces in flight ( with alt + f12 then physics and tick the right case in aero). I didn't do anything special actually. And for my planes it's build B9 and stock parts no tweakscale was used.

I'm playing with KSP 1.3and here are my mods installed:
 FAR
 B9 aerospace
 B9 aerospace HX
 B9 aerospace legacy
 B9 animation modules
 B9 part switch
 Community category kit
 Firespitter (but i've deleted all the parts in the part folder)
 JSI
 KAS
 KIS
 Infernal robotics  (only the with the rework model and also i've deleted the "rework_Utility folder in parts otherwise my game crash when i launch the game )
 Modular Flight Integrator
 Quick Exit
 Smoke Screen
 Trajectories
 TweakScale

**Comment by ferram4** [comment] 2017-06-29 19:37
Which FAR build are you using?

Are ALL of these mods needed?  If not, which ones aren't needed?  And I mean "needed" not, "I don't want to check" because more mods makes the likelihood of reproducing the issue a lot less likely.

Does it happen with just this SSTO, or any vehicle?  Can it be caused with a simpler vehicle?  Does it even need to be flown into space?

**Comment by lilbat** [comment] 2017-07-01 12:25
About the commit : i don't know how to find older commits but this issue happens even with the latest commit.

All the mods aren't needed to make this bug. If i uninstall trajectories it doesn't occur(so only trajectories makes this bug occur with FAR). Also the messed up drag occurs only with parts like wings, control surfaces (when i said that some parts had too little drag it's just because i'm dumb,i think it was working properlly for these parts). 

It happens with all vehicules regardless if i go to space or not.

**Comment by ferram4** [comment] 2017-07-01 22:56
It looks like these aren't forces at all, this is Trajectories' predictions clobbering the aero arrows.  I've added a check to prevent it from doing that, unless it's doing stuff that it should not be doing to try and get info from FAR.

Fix is in the latest dev build.

**Closed by ferram4** 2017-07-01 22:56 UTC
